"""
app/schemas/chat.py

Request/response models for POST /chat — §17, §29. Two named deviations
from §17's literal example JSON, both explained in this project's Stage 5
plan and repeated briefly here since this is the file that encodes them:

  (E) Request field is `conversation_id`, not `session_id`. §17's example
      shows `session_id`, but §4's real state contract field and §29's own
      prose ("loads prior messages for the given `conversation_id`") both
      say `conversation_id` — treated as a stale naming artifact in that
      one example. `conversation_id: str | None = None`: omitted/None
      starts a new conversation (a fresh UUID is generated by
      routes_chat.py); provided resumes one, loading its prior messages
      into `chat_history` per §29.

  (F) Response `category`/`severity` fields: §17's example shows
      `"category": "Performance"`, not a real value in the actual 6-value
      enum (state.py has no "performance" category — that example predates
      the finalized enum). The real response echoes the actual category
      value. `severity` prefers `severity_final`, falling back to
      `severity_initial` (router.resolve_effective_severity) — since
      incident_severity_node doesn't exist until Stage 6, `severity_final`
      is always None this stage, so this is effectively always
      severity_initial for now.
"""

from pydantic import BaseModel

from app.schemas.agent_contracts import SourceRef


class ChatRequest(BaseModel):
    query: str
    customer_id: int
    conversation_id: str | None = None


class ChatResponse(BaseModel):
    answer: str
    category: str | None
    severity: str | None
    retrieval_mode: str | None
    confidence_score: float | None
    confidence_tier: str | None
    sources: list[SourceRef]
    escalated: bool
    flagged_for_review: bool
    trace_id: str
    conversation_id: str
    # Frontend integration pass: both already lived in SupportGraphState
    # (§4 — retrieval_retry_count, reflection_loopback_count) but were never
    # surfaced here, so a client had no way to know whether doc_retrieval's
    # internal retry or reflect_node's loop-back actually fired for this turn.
    retrieval_retry_count: int = 0
    reflection_loopback_count: int = 0
