"""create users table

Revision ID: 055c2255577d
Revises: 
Create Date: 2026-07-19 16:47:07.505945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055c2255577d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False, comment='Surrogate PK; used as handled_by_user_id in the graph state'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Login identifier — unique, case-insensitive in practice'),
    sa.Column('password_hash', sa.String(length=72), nullable=False, comment='bcrypt hash only — raw password is never stored'),
    sa.Column('role', sa.Enum('support_agent', 'admin', name='user_role', create_constraint=True), nullable=False, comment='support_agent or admin — enforced at DB level'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Updated on each successful login; NULL until first login'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=True)
