"""add escalation_log and notification_log tables

Revision ID: 27562268bc44
Revises: f3f3c7873fae
Create Date: 2026-07-25 23:05:51.094463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27562268bc44'
down_revision: Union[str, Sequence[str], None] = 'f3f3c7873fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalation_log',
    sa.Column('escalation_id', sa.Integer(), autoincrement=True, nullable=False, comment='Surrogate PK — referenced by notification_log.escalation_id'),
    sa.Column('trace_id', sa.String(length=255), nullable=False, comment="Correlates to the request's trace_id (Message.trace_id, structured logs)"),
    sa.Column('handled_by_user_id', sa.Integer(), nullable=False, comment='Audit trail (§16) — which support agent was handling the ticket when this fired'),
    sa.Column('ticket_context_json', sa.JSON(), nullable=False, comment='Full context transfer for the human agent — see escalate.build_ticket_context()'),
    sa.Column('reason', sa.Text(), nullable=False, comment="escalate_node's own escalation_reason (EscalationOutput, §39.3), or a fixed fallback string if that LLM call itself failed"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handled_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('escalation_id')
    )
    op.create_index(op.f('ix_escalation_log_trace_id'), 'escalation_log', ['trace_id'], unique=False)
    op.create_table('notification_log',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False, comment='Surrogate PK'),
    sa.Column('escalation_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False, comment="'email' today (Mailtrap) — Slack/PagerDuty are documented, unbuilt extension points (§7)"),
    sa.Column('status', sa.Enum('sent', 'failed', 'failed_permanently', name='notification_status', create_constraint=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['escalation_id'], ['escalation_log.escalation_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notification_log_escalation_id'), 'notification_log', ['escalation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_log_escalation_id'), table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_escalation_log_trace_id'), table_name='escalation_log')
    op.drop_table('escalation_log')
    # ### end Alembic commands ###
