"""add possibly_truncated to tables

Revision ID: 30623f89349f
Revises: 4ff9a4a63aaa
Create Date: 2026-07-22 22:36:45.530779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30623f89349f'
down_revision: Union[str, Sequence[str], None] = '4ff9a4a63aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('possibly_truncated', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment="extract_tables.py's cross-page-stitch fallback flag: this fragment sat near a page bottom but a matching continuation on the next page couldn't be confirmed (§8.2's known find_tables()-per-page limitation) — an honest 'might be incomplete' signal, not a guess. DB-level default, matching this project's own established convention (§21) — every insert path gets false unconditionally, not just pipeline.py's."))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'possibly_truncated')
    # ### end Alembic commands ###
