"""add is_active to users and create password_reset_tokens

Revision ID: 4314520ade09
Revises: ee06f930b272
Create Date: 2026-07-29 16:46:59.953338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4314520ade09'
down_revision: Union[str, Sequence[str], None] = 'ee06f930b272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='References users.user_id this token was issued for'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='sha256 hex digest of the raw token; the raw token itself is never stored'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Token becomes unusable after this timestamp'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='Set once the token is redeemed; NULL means still unused'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Soft-retire flag (§21/§22 convention) — set False to deactivate an account, never hard-deleted'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
