"""add has_unresolved_symbols to tables

Revision ID: 4fb1ea4103e7
Revises: 30623f89349f
Create Date: 2026-07-23 18:25:51.185829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fb1ea4103e7'
down_revision: Union[str, Sequence[str], None] = '30623f89349f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('has_unresolved_symbols', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment="extract_tables.py's ZapfDingbats-glyph flag: this table's source PDF region contains an icon-font character this module doesn't have a visually-confirmed-safe Unicode substitution for (distinct from possibly_truncated — nothing here is missing rows, the concern is cell CONTENT, since the glyph's raw code point collides with an ordinary letter once it's plain text with no font attached). DB-level default, same convention as possibly_truncated (§21) — every insert path gets false unconditionally."))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'has_unresolved_symbols')
    # ### end Alembic commands ###
