"""add ingestion pipeline tables

Revision ID: 4ff9a4a63aaa
Revises: f24af2abbbc7
Create Date: 2026-07-22 11:28:11.113346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy  # NOT auto-added by autogenerate — it renders
# pgvector.sqlalchemy.vector.VECTOR(dim=1536) below (4 occurrences) but
# doesn't know how to import a third-party column type on its own; without
# this line, `alembic upgrade head` would fail with NameError the moment
# upgrade()/downgrade() actually runs. Confirmed by executing the
# generated file as originally emitted before adding this line.

# revision identifiers, used by Alembic.
revision: str = '4ff9a4a63aaa'
down_revision: Union[str, Sequence[str], None] = 'f24af2abbbc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOT auto generated — added after autogenerate's output was tested
    # against a genuinely fresh database (this project's test-DB fixture,
    # not the dev DB, which turned out to already have this extension
    # enabled from some earlier manual/image step outside Alembic's
    # control — masking exactly this gap). Every VECTOR(1536) column
    # below needs the pgvector extension to exist first, or CREATE TABLE
    # fails with `type "vector" does not exist`. Confirmed by running
    # this migration against a fresh DB before adding this line, and
    # again after, per §22's "no table/schema element created outside
    # Alembic" principle — the extension is schema, so Alembic should be
    # the one thing responsible for it, not a step someone has to
    # remember to do by hand on a new database.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_versions',
    sa.Column('version_id', sa.Integer(), autoincrement=True, nullable=False, comment="Surrogate PK — the real per-row identity (see module comment on why document_id can't be)"),
    sa.Column('document_id', sa.String(length=255), nullable=False, comment='Stable identifier for the document across its version history — repeats across rows, not unique'),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='SHA256 hex of the raw file bytes (hashing.hash_bytes()) — §8.3 step 1'),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when this version was ingested'),
    sa.Column('status', sa.Enum('active', 'superseded', name='document_version_status', create_constraint=True), nullable=False, comment='active (current) or superseded — enforced at DB level'),
    sa.Column('doc_title', sa.String(length=255), nullable=True),
    sa.Column('product_version', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('job_id', sa.String(length=255), nullable=False, comment='Generated at request time (UUID string), returned in the 202 response'),
    sa.Column('document_id', sa.String(length=255), nullable=False, comment='References document_versions.document_id logically, no FK constraint (see module comment)'),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='ingestion_job_status', create_constraint=True), nullable=False),
    sa.Column('stats_json', sa.JSON(), nullable=True, comment="§8's step 5: {assets_new, assets_unchanged_skipped, assets_updated, assets_retired}"),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='NULL until the job actually finishes'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_ingestion_jobs_document_id'), 'ingestion_jobs', ['document_id'], unique=False)
    op.create_table('ingested_assets',
    sa.Column('asset_id', sa.Integer(), autoincrement=True, nullable=False, comment='Surrogate PK — referenced by chunks/tables/images/diagram_graphs.asset_id'),
    sa.Column('document_id', sa.String(length=255), nullable=False, comment='References document_versions.document_id logically, no FK constraint (see module comment)'),
    sa.Column('asset_type', sa.String(length=50), nullable=False, comment="'chunk' | 'table' | 'image' | 'diagram'"),
    sa.Column('asset_hash', sa.String(length=64), nullable=False, comment="SHA256 hex of the extracted content — §8.3's entire dedup mechanism reads/diffs this"),
    sa.Column('embedding_id', sa.String(length=255), nullable=True, comment='Identifier of the associated embedding row in whichever asset-type table this asset produced — not a single FK, since which table depends on asset_type (polymorphic)'),
    sa.Column('first_seen_version', sa.Integer(), nullable=True, comment='document_versions.version_id this asset (this exact hash) first appeared in'),
    sa.Column('last_seen_version', sa.Integer(), nullable=True, comment='document_versions.version_id this asset (this exact hash) was last seen in'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment="§8.3's soft-retire flag — set False when a re-ingestion no longer produces this hash, never hard-deleted"),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_header', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['first_seen_version'], ['document_versions.version_id'], ),
    sa.ForeignKeyConstraint(['last_seen_version'], ['document_versions.version_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index(op.f('ix_ingested_assets_asset_hash'), 'ingested_assets', ['asset_hash'], unique=False)
    op.create_index(op.f('ix_ingested_assets_document_id'), 'ingested_assets', ['document_id'], unique=False)
    op.create_table('chunks',
    sa.Column('chunk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text)", persisted=True), nullable=False, comment='DB-generated (STORED), never written by application code — see module comment'),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('section_header', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('product_version', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['ingested_assets.asset_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index(op.f('ix_chunks_category'), 'chunks', ['category'], unique=False)
    op.create_index(op.f('ix_chunks_doc_type'), 'chunks', ['doc_type'], unique=False)
    op.create_index('ix_chunks_embedding_hnsw', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_chunks_product_version'), 'chunks', ['product_version'], unique=False)
    op.create_index('ix_chunks_tsv_gin', 'chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('diagram_graphs',
    sa.Column('diagram_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('graph_json', sa.JSON(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('diagram_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['ingested_assets.asset_id'], ),
    sa.PrimaryKeyConstraint('diagram_id')
    )
    op.create_index(op.f('ix_diagram_graphs_category'), 'diagram_graphs', ['category'], unique=False)
    op.create_index('ix_diagram_graphs_embedding_hnsw', 'diagram_graphs', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('images',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('blob_ref', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['ingested_assets.asset_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_images_category'), 'images', ['category'], unique=False)
    op.create_index('ix_images_embedding_hnsw', 'images', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('tables',
    sa.Column('table_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('text_serialization', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('section_header', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('product_version', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['ingested_assets.asset_id'], ),
    sa.PrimaryKeyConstraint('table_id')
    )
    op.create_index(op.f('ix_tables_category'), 'tables', ['category'], unique=False)
    op.create_index('ix_tables_embedding_hnsw', 'tables', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_tables_product_version'), 'tables', ['product_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Deliberately does NOT DROP EXTENSION vector: an extension is a
    # database-wide object, and dropping it on downgrade risks breaking
    # anything else in the database that came to depend on it in the
    # meantime — not symmetric with the tables below, which only this
    # migration owns.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tables_product_version'), table_name='tables')
    op.drop_index('ix_tables_embedding_hnsw', table_name='tables', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_tables_category'), table_name='tables')
    op.drop_table('tables')
    op.drop_index('ix_images_embedding_hnsw', table_name='images', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_images_category'), table_name='images')
    op.drop_table('images')
    op.drop_index('ix_diagram_graphs_embedding_hnsw', table_name='diagram_graphs', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_diagram_graphs_category'), table_name='diagram_graphs')
    op.drop_table('diagram_graphs')
    op.drop_index('ix_chunks_tsv_gin', table_name='chunks', postgresql_using='gin')
    op.drop_index(op.f('ix_chunks_product_version'), table_name='chunks')
    op.drop_index('ix_chunks_embedding_hnsw', table_name='chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_chunks_doc_type'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_category'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_ingested_assets_document_id'), table_name='ingested_assets')
    op.drop_index(op.f('ix_ingested_assets_asset_hash'), table_name='ingested_assets')
    op.drop_table('ingested_assets')
    op.drop_index(op.f('ix_ingestion_jobs_document_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    # ### end Alembic commands ###
