"""add reasoning trace fields to messages

Revision ID: 7c8dd5055638
Revises: f431f2dfa901
Create Date: 2026-08-02 19:40:29.230412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8dd5055638'
down_revision: Union[str, Sequence[str], None] = 'f431f2dfa901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    flagged_for_review is added with server_default=sa.text('false')
    (adjusted from the raw autogenerate output, which omitted it) because
    this ALTER TABLE runs against a messages table that already has real
    rows (§21's established server_default convention for exactly this
    case — see is_active on users for the precedent). Without it, this
    NOT NULL column addition would fail on any non-empty table.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('category', sa.String(length=50), nullable=True, comment="Frontend integration pass: classify_node's category at the time this (assistant) message was produced — previously only returned live in ChatResponse, never persisted, so a reopened conversation couldn't show it"))
    op.add_column('messages', sa.Column('severity', sa.String(length=50), nullable=True, comment='Frontend integration pass: resolve_effective_severity() output for this turn — same persistence gap as category'))
    op.add_column('messages', sa.Column('retrieval_mode', sa.String(length=50), nullable=True, comment="Frontend integration pass: router_node's retrieval_mode for this turn (RAG/SQL/Hybrid/Critical) — same persistence gap as category"))
    op.add_column('messages', sa.Column('confidence_score', sa.Float(), nullable=True, comment="Frontend integration pass: reflect_node's blended confidence_score (0.3*retrieval_quality + 0.5*llm_self_critique + 0.2*groundedness) for this turn — confidence_tier alone was already persisted, the raw score wasn't"))
    op.add_column('messages', sa.Column('flagged_for_review', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment="Frontend integration pass: router.decide_action()'s QA-sampling flag (§6.1) for this turn — previously only returned live in ChatResponse, never persisted"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'flagged_for_review')
    op.drop_column('messages', 'confidence_score')
    op.drop_column('messages', 'retrieval_mode')
    op.drop_column('messages', 'severity')
    op.drop_column('messages', 'category')
    # ### end Alembic commands ###
