"""create conversations and messages tables

Revision ID: 8390c2c904c7
Revises: 055c2255577d
Create Date: 2026-07-19 23:30:20.000846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8390c2c904c7'
down_revision: Union[str, Sequence[str], None] = '055c2255577d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('conversation_id', sa.String(length=255), nullable=False, comment='Unique conversation identifier (UUID string)'),
    sa.Column('customer_id', sa.Integer(), nullable=False, comment='References pre-existing customers table by ID, but NO foreign key constraint'),
    sa.Column('handled_by_user_id', sa.Integer(), nullable=False, comment='References user_id of the support agent handling this conversation'),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'escalated', 'closed', name='conversation_status', create_constraint=True), nullable=False, comment='Status of the conversation per §38 — enforced at DB level'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when the conversation was started'),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when the last message was sent/received'),
    sa.ForeignKeyConstraint(['handled_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False, comment='Surrogate PK for messages'),
    sa.Column('conversation_id', sa.String(length=255), nullable=False, comment='References the conversation this message belongs to'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='Role of the message author (e.g. user, assistant)'),
    sa.Column('content', sa.Text(), nullable=False, comment='The text content of the message'),
    sa.Column('trace_id', sa.String(length=255), nullable=False, comment='Observability/Langfuse trace ID'),
    sa.Column('confidence_tier', sa.String(length=50), nullable=True, comment='Confidence level of the response (e.g., High, Medium, Low)'),
    sa.Column('escalation_flag', sa.Boolean(), nullable=False, comment='True if this message triggered or is part of an escalation'),
    sa.Column('sources_json', sa.JSON(), nullable=True, comment='JSON serialization of citation/sources references'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when the message was created'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('messages')
    op.drop_table('conversations')
    sa.Enum(name='conversation_status').drop(op.get_bind(), checkfirst=True)
