"""add course-provided tables

Revision ID: ce9eb2de85fe
Revises: 8390c2c904c7
Create Date: 2026-07-20 22:12:48.335208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9eb2de85fe'
down_revision: Union[str, Sequence[str], None] = '8390c2c904c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('subscription_tier', sa.String(length=50), nullable=True),
    sa.Column('account_status', sa.String(length=50), nullable=True),
    sa.Column('sla_level', sa.String(length=50), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('incident_logs',
    sa.Column('incident_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('affected_region', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('resolution_status', sa.String(length=50), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('escalation_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_table('knowledge_article_usage',
    sa.Column('article_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_title', sa.String(length=200), nullable=True),
    sa.Column('product_version', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('known_issue_flag', sa.Boolean(), nullable=True),
    sa.Column('internal_confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('support_tickets',
    sa.Column('ticket_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('issue_category', sa.String(length=100), nullable=True),
    sa.Column('severity_level', sa.String(length=50), nullable=True),
    sa.Column('ticket_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_team', sa.String(length=100), nullable=True),
    sa.Column('escalation_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_tickets')
    op.drop_table('knowledge_article_usage')
    op.drop_table('incident_logs')
    op.drop_table('customers')
    # ### end Alembic commands ###
