"""add server_default to timestamp columns

Revision ID: f24af2abbbc7
Revises: ce9eb2de85fe
Create Date: 2026-07-20 22:26:27.014141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f24af2abbbc7'
down_revision: Union[str, Sequence[str], None] = 'ce9eb2de85fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_comment='UTC timestamp when the conversation was started',
               existing_nullable=False)
    op.alter_column('conversations', 'last_message_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_comment='UTC timestamp when the last message was sent/received',
               existing_nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_comment='UTC timestamp when the message was created',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_comment='Row creation timestamp (UTC)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_comment='Row creation timestamp (UTC)',
               existing_nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_comment='UTC timestamp when the message was created',
               existing_nullable=False)
    op.alter_column('conversations', 'last_message_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_comment='UTC timestamp when the last message was sent/received',
               existing_nullable=False)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_comment='UTC timestamp when the conversation was started',
               existing_nullable=False)
    # ### end Alembic commands ###
