"""add tsv columns to tables, images, diagram_graphs

Revision ID: f3f3c7873fae
Revises: 4fb1ea4103e7
Create Date: 2026-07-24 09:35:30.151816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3f3c7873fae'
down_revision: Union[str, Sequence[str], None] = '4fb1ea4103e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagram_graphs', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', COALESCE(caption, ''))", persisted=True), nullable=False, comment="DB-generated (STORED), never written by application code — see module comment. caption is nullable (None until parse_diagram() has run, §8.3), so COALESCE(..., '') keeps to_tsvector() from ever receiving NULL."))
    op.create_index('ix_diagram_graphs_tsv_gin', 'diagram_graphs', ['tsv'], unique=False, postgresql_using='gin')
    op.add_column('images', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', COALESCE(caption, ''))", persisted=True), nullable=False, comment="DB-generated (STORED), never written by application code — see module comment. caption is nullable (None until caption_image() has run, §8.3), so COALESCE(..., '') keeps to_tsvector() from ever receiving NULL."))
    op.create_index('ix_images_tsv_gin', 'images', ['tsv'], unique=False, postgresql_using='gin')
    op.add_column('tables', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text_serialization)", persisted=True), nullable=False, comment="DB-generated (STORED), never written by application code — see module comment. text_serialization is NOT NULL already, so no COALESCE needed here (unlike Image/DiagramGraphRow's caption)."))
    op.create_index('ix_tables_tsv_gin', 'tables', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tables_tsv_gin', table_name='tables', postgresql_using='gin')
    op.drop_column('tables', 'tsv')
    op.drop_index('ix_images_tsv_gin', table_name='images', postgresql_using='gin')
    op.drop_column('images', 'tsv')
    op.drop_index('ix_diagram_graphs_tsv_gin', table_name='diagram_graphs', postgresql_using='gin')
    op.drop_column('diagram_graphs', 'tsv')
    # ### end Alembic commands ###
