import os
from pathlib import Path
import asyncio
import requests
import json

from dotenv import load_dotenv
from google import genai

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import StreamingResponse, JSONResponse

from slowapi import Limiter
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded

from app.schemas import ConceptRequest, ExplanationResponse, ErrorResponse


# ============================================================
# Load Environment Variables
# ============================================================

# Go up two levels to reach Building_Agentic_AI_Systems
BASE_DIR = Path(__file__).resolve().parents[4]

env_path = BASE_DIR / ".env"

load_dotenv(dotenv_path=env_path)

api_key = os.getenv("GEMINI_API_KEY")
if not api_key:
    raise ValueError("GEMINI_API_KEY not found in environment variables")

base_url = os.getenv("GEMINI_ENDPOINT")
if not base_url:
    raise ValueError("GEMINI_ENDPOINT not found in environment variables")

gemini_model = os.getenv("GEMINI_MODEL")
if not gemini_model:    
    raise ValueError("GEMINI_MODEL not found in environment variables")

client = genai.Client(api_key=api_key)



# ============================================================
# FastAPI App and Rate Limiter Setup
# ============================================================

app = FastAPI(
    title="Study Buddy AI Tutor API",
    description="AI-powered tutoring API with Cloud and Local models",
    version="1.0.0",
    contact={
        "name": "Yeko Fes",
        "email": "yekofes792@netoiu.com"
    }
)

limiter = Limiter(key_func=get_remote_address)
app.state.limiter = limiter

@app.exception_handler(RateLimitExceeded)
async def rate_limit_handler(request: Request, exc: RateLimitExceeded):
    return JSONResponse(
        status_code=429,
        content={
            "error": "Rate limit exceeded",
            "detail": "Maximum 3 requests per minute allowed."
            }
    )
# ============================================================
# Cloud Model for Structured Explanation
# ============================================================

@app.post(
    "/explain",
    response_model = ExplanationResponse,
    summary = "Generate structured explanation using Gemini (Cloud)",
    description = "Returns a clear and structured explanation of a given concept using the Gemini cloud model.",
    responses = {400: {"model": ErrorResponse}, 429: {"description": "Rate limit exceeded"}}
    )
@limiter.limit("3/minute")

def explain_concept(request: Request, data: ConceptRequest):
    """
    Accepts a concept and difficulty level.
    Returns a factual explanation generated by Gemini.
    """
    
    try:
        prompt = f"""You are a factual tutor.
        Provide a clear and structured explanation of the concept: {data.concept}.
        Explain it for a {data.level} learner.
        Keep it structured."""
        response = client.models.generate_content(
            model = gemini_model,
            contents = prompt
        )

        return ExplanationResponse(
            concept = data.concept,
            explanation = response.text,
            model_used = f"Cloud Model: {gemini_model}",
            confidence = 0.95
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error generating explanation: {str(e)}")
    
# ============================================================
# Local LLM For Personalized Explanation
# ============================================================

@app.post(
    "/personalize",
    response_model = ExplanationResponse,
    summary = "Generate creative explanation using Local Ollama model",
    description = "Returns a creative and engaging explanation using the local phi3:mini model.",
    responses = {400: {"model": ErrorResponse}, 429: {"description": "Rate limit exceeded"}}
    )
@limiter.limit("3/minute")

def personalize_concept(request: Request, data: ConceptRequest):
    """
    Accepts a concept and difficulty level.
    Returns a creative explanation generated locally using Ollama.
    """
    
    try:
        url = "http://localhost:11434/api/generate"
        
        prompt = (
                f"Rewrite this technical explanation in a highly engaging, fun, "
                f"and personally relatable story or creative analogy for a {data.level} learner "
                f"exploring Agentic AI. Be creative and do not exceed 4 sentences.\n\n"
                f"Explain the concept of:\n\n---\n{data.concept}"
            )
        
        payload = {
                "model": "phi3:mini",
                "prompt": prompt,
                "stream": False
            }
        
        local_response = requests.post(url, json=payload)
        
        if local_response.status_code == 200:
            personalized_explanation = local_response.json()["response"]
            return ExplanationResponse(
                concept = data.concept,
                explanation = personalized_explanation,
                model_used = "Local Model: phi3:mini",
                confidence = 0.85
            )
        else:
            raise HTTPException(status_code=503, detail=f"Local model error: {local_response.text}")
    
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error generating personalized explanation: {str(e)}")
    
    
# ============================================================
# Streaming
# ============================================================

@app.post(
    "/explain/stream",
    summary = "Stream structured explanation from Gemini",
    description = "Streams explanation token-by-token in real time from the cloud model."
    )
@limiter.limit("3/minute")

async def stream_explanation(request: Request, data: ConceptRequest):
    
    async def event_generator():
        try:
            prompt = f"""You are a factual tutor.
            Provide a clear and structured explanation of the concept: {data.concept}.
            Explain it for a {data.level} learner.
            Keep it structured."""
            response = client.models.generate_content_stream(
                model = gemini_model,
                contents = prompt
            )

            for chunk in response:
                if chunk.text:
                    yield chunk.text
                    await asyncio.sleep(0.02)
        
        except Exception as e:
            yield f"[ERROR: Streaming Failed] {str(e)}"
            
    return StreamingResponse(event_generator(), media_type="text/plain")



@app.post(
    "/personalize/stream",
    summary = "Stream creative explanation from Local model",
    description = "Streams explanation token-by-token in real time from the local Ollama model."
    )
@limiter.limit("3/minute")

async def stream_personalized(request: Request, data: ConceptRequest):
    
    async def event_generator():
        try:
            url = "http://localhost:11434/api/generate"
            
            prompt = (
                    f"Rewrite this technical explanation in a highly engaging, fun, "
                    f"and personally relatable story or creative analogy for a {data.level} learner "
                    f"exploring Agentic AI. Be creative and do not exceed 4 sentences.\n\n"
                    f"Explain the concept of:\n\n---\n{data.concept}"
                )
            
            payload = {
                    "model": "phi3:mini",
                    "prompt": prompt,
                    "stream": True
                }
            
            with requests.post(url, json=payload, stream=True) as local_response:
                if local_response.status_code == 200:
                    for line in local_response.iter_lines():
                        if line:
                            decoded = line.decode("utf-8")
                            json_data = json.loads(decoded)

                            if "response" in json_data:
                                yield json_data["response"]

                            await asyncio.sleep(0.02)
                        
                else:
                    yield f"[ERROR: Local Model Failed] Status Code: {local_response.status_code}"
        
        except Exception as e:
            yield f"[ERROR: Streaming Failed] {str(e)}"
    
    return StreamingResponse(event_generator(), media_type="text/plain")
